---
- name: Deploy Docker and Nginx with load balancing
  hosts: localhost
  connection: local
  become: yes
  vars:
    docker_username: prime2270
    app_image: "{{ docker_username }}/my_first_echo_server_python:1.2"
    container_ports: [8001, 8002, 8003]
    dockerhub_username: "your_username"
    dockerhub_password: "your_password"

  tasks:
    - name: Ensure docker-py is installed
      pip:
        name: docker
        state: present
        executable: pip3

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        email: ""

    - name: Run app containers
      docker_container:
        name: "app_{{ item }}"
        image: "{{ app_image }}"
        ports: ["{{ item }}:8000"]
        env:
          AUTHOR: "Konstantin Yakovlev"
        restart_policy: unless-stopped
      loop: "{{ container_ports }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx load balancing
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted